name = "crowdplay"
main = "apps/worker/src/index.ts"
compatibility_date = "2026-04-02"

[assets]
directory = "./apps/web/dist"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "GAME_SESSIONS"
class_name = "GameSessionDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameSessionDurableObject"]

[[d1_databases]]
binding = "DB"
database_name = "crowdplay"
database_id = "7af1e559-b162-4bbc-b847-3f7385c71a49"
migrations_dir = "./migrations"

[vars]
APP_NAME = "CrowdPlay"
